/** Hedging vocabulary used for PR and documentation density scoring (~80 terms). */
export const HEDGING_TERMS: readonly string[] = [
  'arguably',
  'as a rule',
  'basically',
  'by and large',
  'can potentially',
  'could potentially',
  'essentially',
  'fairly',
  'for the most part',
  'generally',
  'in general',
  'in most cases',
  'in many cases',
  'in some cases',
  'it appears that',
  'it could be argued',
  'it is important to note',
  'it is worth noting',
  'it may be',
  'it might be',
  'it should be noted',
  'it seems',
  'it seems like',
  'just',
  'kind of',
  'largely',
  'may',
  'might',
  'more or less',
  'mostly',
  'often',
  'on the whole',
  'perhaps',
  'possibly',
  'potentially',
  'presumably',
  'probably',
  'quite',
  'rather',
  'relatively',
  'seemingly',
  'simply',
  'somewhat',
  'sort of',
  'supposedly',
  'tends to',
  'to some degree',
  'to some extent',
  'typically',
  'usually',
  'virtually',
  'widely',
  'arguably speaking',
  'broadly speaking',
  'generally speaking',
  'in a sense',
  'in a way',
  'in effect',
  'in practice',
  'in theory',
  'more often than not',
  'not necessarily',
  'often times',
  'one could say',
  'one might say',
  'one possible',
  'one potential',
  'to a certain extent',
  'to a degree',
  'under certain circumstances',
  'under normal circumstances',
  'as needed',
  'as required',
  'as appropriate',
  'where applicable',
  'where possible',
  'if applicable',
  'if needed',
  'if required',
  'when appropriate',
  'when needed',
  'when possible',
  'depending on',
  'based on needs',
  'at times',
  'from time to time',
  'in certain situations',
  'in many situations',
  'in various cases',
  'all things considered',
] as const;
