/** AI-style imperative verbs common in low-information commit messages. */
export const IMPERATIVE_VERBS: readonly string[] = [
  'add',
  'update',
  'fix',
  'remove',
  'delete',
  'refactor',
  'improve',
  'enhance',
  'implement',
  'create',
  'modify',
  'change',
  'clean',
  'cleanup',
  'bump',
  'merge',
  'revert',
  'rename',
  'move',
  'adjust',
  'optimize',
  'simplify',
  'format',
  'lint',
  'test',
  'docs',
  'chore',
] as const;
